"use strict";

CONCEPT_META.rnn={
  category:"Deep Learning",
  title:"RNN & LSTM Playground",
  summary:"Edit a sequence and watch recurrent state, gated memory and first-input influence evolve through time.",
  question:"How can a network remember useful information and decide what to forget?"
};

const RNN_PLAY_PRESETS={
  remember:{label:"Remember the first value",values:[1,0,0,0,0,0,0,0]},
  recent:{label:"Detect a recent pulse",values:[0,0,0,0,0,1,0,0]},
  trend:{label:"Accumulate a trend",values:[-.9,-.6,-.3,0,.3,.6,.9]},
  distractors:{label:"Signal with distractors",values:[1,.8,-.9,.7,-.8,.6,-.7,0]},
  longgap:{label:"Long-gap memory",values:[1,0,0,0,0,0,0,0,0,0]}
};

function rnnPlaySigmoid(value){return 1/(1+Math.exp(-clamp(value,-18,18)))}
function rnnPlayForward(sequence,model,options){
  let h=0,c=0;
  return sequence.map((x,index)=>{
    const previousH=h,previousC=c;
    if(model==="rnn"){
      const z=options.inputWeight*x+options.recurrent*previousH,hValue=options.activation==="linear"?z:Math.tanh(z),derivative=options.activation==="linear"?1:1-hValue*hValue;h=hValue;c=h;
      return {index,x,previousH,previousC,z,h,c,derivative,localInfluence:options.recurrent*derivative,f:null,i:null,g:null,o:null};
    }
    const f=rnnPlaySigmoid(options.forgetBias+.15*x+.2*previousH),i=rnnPlaySigmoid(options.writeBias+1.1*x-.25*previousH),g=Math.tanh(options.inputWeight*x+.35*options.recurrent*previousH),o=rnnPlaySigmoid(.8*x+.2*previousH);c=f*previousC+i*g;h=o*Math.tanh(c);
    return {index,x,previousH,previousC,z:null,h,c,f,i,g,o,derivative:null,localInfluence:f};
  });
}
function rnnPlayInfluence(sequence,model,options){
  const baseline=rnnPlayForward(sequence,model,options),epsilon=1e-4,changed=[...sequence];changed[0]+=epsilon;const perturbed=rnnPlayForward(changed,model,options);
  return baseline.map((state,index)=>Math.abs((perturbed[index].h-state.h)/epsilon));
}
function rnnPlayPresetOptions(){return Object.entries(RNN_PLAY_PRESETS).map(([key,preset])=>[key,preset.label]).concat([["custom","Custom sequence"]])}

function setupRnnPlayground(){
  setConcept(
    CONCEPT_META.rnn,
    "Sequence playground",
    "A recurrent cell reused across time",
    "Edit the sequence, select a time step, and inspect the calculation. Click an LSTM gate for its role; use left and right arrow keys to move through time.",
    "<strong>Start here</strong><p>Use <b>Remember the first value</b>. Advance to the final step with a simple RNN, then compare it with the LSTM using exactly the same sequence.</p>"
  );
  conceptElements.controls.innerHTML=
    '<span class="field-label">Visualization</span><div class="train-view-switch rnn-view-switch" role="radiogroup" aria-label="Recurrent-network visualization"><label><input id="rnnViewMechanism" type="radio" name="rnnView" value="mechanism" checked><span>Cell &amp; gates</span></label><label><input id="rnnViewCompare" type="radio" name="rnnView" value="compare"><span>RNN vs LSTM</span></label></div>'+
    '<div class="train-control-section"><span class="train-control-heading">1 · Sequence</span>'+selectControl("rnnPreset","Sequence preset",rnnPlayPresetOptions())+'<span class="field-label">Editable values</span><div class="rnn-sequence-editor" id="rnnSequenceEditor"></div></div>'+
    '<div class="train-control-section"><span class="train-control-heading">2 · Cell</span>'+selectControl("rnnModel","Focused cell",[["rnn","Simple RNN"],["lstm","LSTM"]])+selectControl("rnnActivation","RNN activation",[["tanh","Tanh"],["linear","Linear · can explode"]])+'</div>'+
    '<div class="train-control-section"><span class="train-control-heading">3 · Signal flow</span>'+rangeControl("rnnInputWeight","Input strength","wₓ",.2,2,.1,1.2)+rangeControl("rnnStrength","Recurrent strength","a",0,1.6,.05,.75)+'</div>'+
    '<div class="train-control-section"><span class="train-control-heading">4 · LSTM gates</span><div id="rnnGateControls">'+rangeControl("rnnForget","Forget bias","bᶠ",-3,3,.1,1)+rangeControl("rnnWrite","Write bias","bⁱ",-3,3,.1,-.25)+'</div></div>'+
    '<div class="control"><label for="rnnStep">Current step <em>t</em><output id="rnnStepOut">1</output></label><input id="rnnStep" type="range" min="1" max="8" step="1" value="1"></div>';
  conceptElements.actions.innerHTML='<button class="button" id="rnnPrevious" type="button">Previous step</button><button class="button primary" id="rnnNext" type="button">Next step</button><button class="button" id="rnnAuto" type="button">▶ Play</button><button class="button quiet" id="rnnAdd" type="button">Add step</button><button class="button quiet" id="rnnRemove" type="button">Remove step</button><button class="button quiet" id="rnnReset" type="button">Restart</button>';
  legend([{label:"Input xₜ",color:conceptPalette.blue},{label:"RNN hidden state",color:conceptPalette.green},{label:"LSTM hidden state",color:conceptPalette.purple},{label:"Cell memory cₜ",color:conceptPalette.orange}]);
  setExplanation(
    '<p>A recurrent network uses the previous hidden state when processing the next input. An LSTM adds a separate cell state and gates that control what is retained, written and revealed.</p><div class="try-card"><strong>Try this</strong><p>Choose <b>Long-gap memory</b>. Lower the RNN recurrent strength, then raise the LSTM forget bias. Compare first-input influence at the final step.</p></div><p class="concept-readout" id="rnnReadout"><strong>Selected step:</strong> the first input has just entered the recurrent cell.</p>',
    '<div class="formula compact" id="rnnFormula">hₜ = tanh(wₓxₜ + ahₜ₋₁)</div><p id="rnnMath"></p>',
    '<ul class="plain-list"><li>A simple RNN repeatedly transforms one hidden state. Values and gradients can fade, saturate or grow across many repetitions.</li><li>The forget gate controls how much previous cell memory continues forward.</li><li>The input gate controls how strongly candidate content is written into memory.</li><li>The output gate controls how much cell memory becomes visible as the hidden state.</li><li>The comparison chart measures local sensitivity to the first input using a tiny numerical perturbation.</li><li>These are scalar teaching cells. Real networks use learned vectors and matrices but repeat the same principles.</li></ul>'
  );

  conceptState={view:"mechanism",model:"rnn",preset:"remember",sequence:[...RNN_PLAY_PRESETS.remember.values],step:0,activation:"tanh",inputWeight:1.2,recurrent:.75,forgetBias:1,writeBias:-.25,selectedGate:"forget",stateAreas:[],gateAreas:[]};
  const options=()=>({activation:conceptState.activation,inputWeight:conceptState.inputWeight,recurrent:conceptState.recurrent,forgetBias:conceptState.forgetBias,writeBias:conceptState.writeBias});
  const forward=model=>rnnPlayForward(conceptState.sequence,model,options());
  const updateStepControl=()=>{conceptState.step=clamp(conceptState.step,0,conceptState.sequence.length-1);const control=$("#rnnStep");control.max=conceptState.sequence.length;control.value=conceptState.step+1;$("#rnnStepOut").textContent=`${conceptState.step+1} / ${conceptState.sequence.length}`};
  const updateCellControls=()=>{const rnn=conceptState.model==="rnn",activation=$("#rnnActivation"),gateControls=$("#rnnGateControls");if(activation)activation.disabled=!rnn;if(gateControls)gateControls.classList.toggle("disabled",rnn)};
  const renderSequenceEditor=()=>{const editor=$("#rnnSequenceEditor");editor.innerHTML=conceptState.sequence.map((value,index)=>`<label class="${index===conceptState.step?"active":""}"><span>x${index+1}</span><input type="number" min="-1.5" max="1.5" step="0.1" value="${Math.round(value*10)/10}" data-rnn-value="${index}" aria-label="Sequence value at step ${index+1}"></label>`).join("");editor.querySelectorAll("[data-rnn-value]").forEach(input=>input.addEventListener("input",event=>{const index=Number(event.target.dataset.rnnValue);conceptState.sequence[index]=clamp(Number(event.target.value)||0,-1.5,1.5);conceptState.preset="custom";$("#rnnPreset").value="custom";conceptRender()}))};
  const syncEditorHighlight=()=>document.querySelectorAll("[data-rnn-value]").forEach(input=>input.parentElement.classList.toggle("active",Number(input.dataset.rnnValue)===conceptState.step));
  const arrow=(context,x1,y1,x2,y2,color="#8094a5",width=1.7)=>{context.beginPath();context.moveTo(x1,y1);context.lineTo(x2,y2);context.strokeStyle=color;context.lineWidth=width;context.stroke();const angle=Math.atan2(y2-y1,x2-x1);context.beginPath();context.moveTo(x2,y2);context.lineTo(x2-6*Math.cos(angle-.45),y2-6*Math.sin(angle-.45));context.lineTo(x2-6*Math.cos(angle+.45),y2-6*Math.sin(angle+.45));context.closePath();context.fillStyle=color;context.fill()};
  const roundedBox=(context,box,fill,stroke,label,value,active=false)=>{context.beginPath();context.roundRect(box.x,box.y,box.w,box.h,7);context.fillStyle=fill;context.fill();context.strokeStyle=active?conceptPalette.ink:stroke;context.lineWidth=active?3:1.5;context.stroke();context.fillStyle=conceptPalette.ink;context.textAlign="center";context.font="800 10px system-ui";context.fillText(label,box.x+box.w/2,box.y+box.h*.42);context.font="700 10px system-ui";context.fillText(fmt(value,2),box.x+box.w/2,box.y+box.h*.72)};
  const drawTimeline=(context,size,states,model)=>{
    const n=states.length,left=size.width<560?58:48,right=size.width-(size.width<560?12:34),spacing=(right-left)/Math.max(1,n-1),inputY=57,hiddenY=132,memoryY=197,radius=Math.min(18,spacing*.28);conceptState.stateAreas=[];
    context.fillStyle=conceptPalette.muted;context.font="800 10px system-ui";context.textAlign="left";context.fillText("EDITABLE SEQUENCE",12,20);context.fillText("INPUT",5,inputY+4);context.fillText("STATE",5,hiddenY+4);if(model==="lstm")context.fillText("MEMORY",3,memoryY+4);
    for(let index=0;index<n-1;index++){const x1=left+index*spacing+radius,x2=left+(index+1)*spacing-radius,processed=index<conceptState.step;arrow(context,x1,hiddenY,x2,hiddenY,processed?conceptPalette.green+"bb":"#b8c6d0",1.6);if(model==="lstm"){context.beginPath();context.moveTo(left+index*spacing+radius,memoryY);context.lineTo(left+(index+1)*spacing-radius,memoryY);context.strokeStyle=processed?conceptPalette.orange+"bb":"#c6cdd3";context.lineWidth=2.5;context.stroke()}}
    states.forEach((state,index)=>{const x=left+index*spacing,processed=index<=conceptState.step,active=index===conceptState.step,alpha=processed?1:.26,inputBox={x:x-radius,y:inputY-radius,w:radius*2,h:radius*2};context.save();context.globalAlpha=alpha;arrow(context,x,inputY+radius,x,hiddenY-radius,conceptPalette.blue+"aa",1.4);roundedBox(context,inputBox,"#e1eef7",conceptPalette.blue,`x${index+1}`,state.x,active);context.beginPath();context.arc(x,hiddenY,radius,0,Math.PI*2);context.fillStyle=model==="rnn"?"#dff1e8":"#ebe7f7";context.fill();context.strokeStyle=active?conceptPalette.ink:(model==="rnn"?conceptPalette.green:conceptPalette.purple);context.lineWidth=active?3:1.6;context.stroke();context.fillStyle=conceptPalette.ink;context.textAlign="center";context.font="800 9px system-ui";context.fillText(`h${index+1}`,x,hiddenY-2);context.font="700 9px system-ui";context.fillText(fmt(state.h,2),x,hiddenY+10);if(model==="lstm"){arrow(context,x,hiddenY+radius,x,memoryY-radius,conceptPalette.purple+"88",1.3);context.beginPath();context.roundRect(x-radius,memoryY-radius,radius*2,radius*2,5);context.fillStyle="#fff0e5";context.fill();context.strokeStyle=active?conceptPalette.ink:conceptPalette.orange;context.lineWidth=active?3:1.5;context.stroke();context.fillStyle=conceptPalette.ink;context.font="800 9px system-ui";context.fillText(`c${index+1}`,x,memoryY-2);context.font="700 9px system-ui";context.fillText(fmt(state.c,2),x,memoryY+10)}context.restore();conceptState.stateAreas.push({x:x-radius-4,y:inputY-radius-4,w:radius*2+8,h:(model==="lstm"?memoryY: hiddenY)-inputY+radius*2+8,index})});
  };
  const drawRnnCell=(context,size,state,influence)=>{
    const y=275,gap=size.width<560?8:18,margin=size.width<560?12:50,boxW=(size.width-margin*2-gap*3)/4,boxH=58,boxes=Array.from({length:4},(_,index)=>({x:margin+index*(boxW+gap),y,w:boxW,h:boxH}));
    arrow(context,boxes[0].x+boxW,boxes[0].y+boxH/2,boxes[1].x-5,boxes[1].y+boxH/2);arrow(context,boxes[1].x+boxW,boxes[1].y+boxH/2,boxes[2].x-5,boxes[2].y+boxH/2);arrow(context,boxes[2].x+boxW,boxes[2].y+boxH/2,boxes[3].x-5,boxes[3].y+boxH/2);
    roundedBox(context,boxes[0],"#edf3f7","#91a5b4","previous h",state.previousH);roundedBox(context,boxes[1],"#e3eff7",conceptPalette.blue,"wₓxₜ",conceptState.inputWeight*state.x);roundedBox(context,boxes[2],"#fff0e5",conceptPalette.orange,"sum z",state.z);roundedBox(context,boxes[3],"#dff1e8",conceptPalette.green,conceptState.activation,state.h,true);
    const bar={x:margin,y:375,w:size.width-margin*2,h:16},normalized=clamp((Math.log10(Math.max(influence,1e-4))+4)/6,0,1);context.fillStyle=conceptPalette.ink;context.font="800 10px system-ui";context.textAlign="left";context.fillText("INFLUENCE OF THE FIRST INPUT AT THIS STEP",bar.x,bar.y-10);context.fillStyle="#e2e9ee";context.fillRect(bar.x,bar.y,bar.w,bar.h);context.fillStyle=influence>1?conceptPalette.red:conceptPalette.green;context.fillRect(bar.x,bar.y,bar.w*normalized,bar.h);context.fillStyle=conceptPalette.ink;context.font="800 10px system-ui";context.fillText(fmt(influence,4),bar.x+6,bar.y+12);context.fillStyle=conceptPalette.muted;context.font="700 10px system-ui";context.fillText(influence<.02?"The first input now has very little effect.":influence>1?"Sensitivity is growing across repeated steps.":"Some first-input influence remains.",bar.x,bar.y+39);
  };
  const gateDescriptions={forget:"keeps a fraction of the previous cell memory",input:"controls how strongly candidate content is written",candidate:"proposes new content from the current input",output:"controls how much cell memory becomes visible"};
  const drawLstmCell=(context,size,state)=>{
    const mobile=size.width<560,startX=mobile?88:size.width*.29,barW=mobile?Math.min(185,size.width-145):Math.min(300,size.width*.39),startY=250,gap=34,gates=[{key:"forget",label:"forget f",value:state.f,color:conceptPalette.orange},{key:"input",label:"input i",value:state.i,color:conceptPalette.blue},{key:"candidate",label:"candidate g",value:state.g,color:conceptPalette.green},{key:"output",label:"output o",value:state.o,color:conceptPalette.purple}];conceptState.gateAreas=[];
    context.fillStyle=conceptPalette.ink;context.font="800 10px system-ui";context.textAlign="left";context.fillText("GATES AT THE SELECTED STEP",startX,startY-18);
    gates.forEach((gate,index)=>{const y=startY+index*gap,selected=conceptState.selectedGate===gate.key;context.fillStyle=conceptPalette.muted;context.font="700 10px system-ui";context.textAlign="right";context.fillText(gate.label,startX-8,y+12);context.fillStyle="#e2e9ee";context.fillRect(startX,y,barW,16);if(gate.key==="candidate"){const center=startX+barW/2;context.fillStyle=gate.color;context.fillRect(center,y,gate.value*barW/2,16);context.beginPath();context.moveTo(center,y);context.lineTo(center,y+16);context.strokeStyle="#8295a5";context.stroke()}else{context.fillStyle=gate.color;context.fillRect(startX,y,barW*gate.value,16)}context.strokeStyle=selected?conceptPalette.ink:"#b7c5cf";context.lineWidth=selected?2.5:1;context.strokeRect(startX,y,barW,16);context.fillStyle=conceptPalette.ink;context.font="800 10px system-ui";context.textAlign="left";context.fillText(fmt(gate.value,2),startX+barW+7,y+12);conceptState.gateAreas.push({x:startX,y,w:barW+38,h:18,gate:gate.key})});
    if(!mobile){const previous={x:25,y:274,w:105,h:58},memory={x:size.width-140,y:260,w:112,h:58},hidden={x:size.width-140,y:354,w:112,h:58};roundedBox(context,previous,"#fff0e5",conceptPalette.orange,"previous c",state.previousC);roundedBox(context,memory,"#fff0e5",conceptPalette.orange,"new memory c",state.c,true);roundedBox(context,hidden,"#ebe7f7",conceptPalette.purple,"visible h",state.h);arrow(context,previous.x+previous.w,previous.y+previous.h/2,startX-10,previous.y+previous.h/2,conceptPalette.orange);arrow(context,startX+barW+44,memory.y+memory.h/2,memory.x-7,memory.y+memory.h/2,conceptPalette.orange);arrow(context,memory.x+memory.w/2,memory.y+memory.h,hidden.x+hidden.w/2,hidden.y-6,conceptPalette.purple)}
    else{context.fillStyle="#edf3f6";context.fillRect(12,398,size.width-24,40);context.fillStyle=conceptPalette.ink;context.font="800 11px system-ui";context.textAlign="center";context.fillText(`cₜ = ${fmt(state.c,3)}   ·   hₜ = ${fmt(state.h,3)}`,size.width/2,423)}
  };
  const drawLineChart=(context,chart,series,current,minValue,maxValue,title)=>{
    context.fillStyle=conceptPalette.ink;context.font="800 10px system-ui";context.textAlign="left";context.fillText(title,chart.x,chart.y-11);context.strokeStyle="#dbe4ea";context.lineWidth=1;for(let line=0;line<=4;line++){const y=chart.y+line/4*chart.h;context.beginPath();context.moveTo(chart.x,y);context.lineTo(chart.x+chart.w,y);context.stroke()}context.strokeStyle="#91a4b2";context.strokeRect(chart.x,chart.y,chart.w,chart.h);const x=index=>chart.x+index/Math.max(1,conceptState.sequence.length-1)*chart.w,y=value=>chart.y+chart.h-(value-minValue)/(maxValue-minValue||1)*chart.h;
    series.forEach(item=>{context.beginPath();item.values.forEach((value,index)=>{const px=x(index),py=y(clamp(value,minValue,maxValue));index?context.lineTo(px,py):context.moveTo(px,py)});context.strokeStyle=item.color;context.lineWidth=2.7;context.stroke();item.values.forEach((value,index)=>{context.beginPath();context.arc(x(index),y(clamp(value,minValue,maxValue)),index===current?4.5:2.6,0,Math.PI*2);context.fillStyle=item.color;context.globalAlpha=index<=current?1:.28;context.fill();context.globalAlpha=1})});const marker=x(current);context.save();context.setLineDash([4,3]);context.beginPath();context.moveTo(marker,chart.y);context.lineTo(marker,chart.y+chart.h);context.strokeStyle=conceptPalette.ink;context.lineWidth=1.4;context.stroke();context.restore();context.fillStyle=conceptPalette.muted;context.font="700 9px system-ui";context.textAlign="center";conceptState.sequence.forEach((_,index)=>context.fillText(String(index+1),x(index),chart.y+chart.h+14));context.textAlign="left";
  };
  const drawComparison=(context,size,rnnStates,lstmStates,rnnInfluence,lstmInfluence)=>{
    const margin=size.width<560?38:54,right=18,width=size.width-margin-right,topChart={x:margin,y:50,w:width,h:140},bottomChart={x:margin,y:264,w:width,h:116},stateLimit=Math.max(1.1,...rnnStates.map(state=>Math.abs(state.h)),...lstmStates.map(state=>Math.abs(state.h)))*1.08;
    drawLineChart(context,topChart,[{values:rnnStates.map(state=>state.h),color:conceptPalette.green},{values:lstmStates.map(state=>state.h),color:conceptPalette.purple}],conceptState.step,-stateLimit,stateLimit,"HIDDEN STATE ACROSS THE SAME SEQUENCE");
    const log=value=>Math.log10(Math.max(value,1e-4));drawLineChart(context,bottomChart,[{values:rnnInfluence.map(log),color:conceptPalette.green},{values:lstmInfluence.map(log),color:conceptPalette.purple}],conceptState.step,-4,2,"FIRST-INPUT INFLUENCE · LOG₁₀ SCALE");
    context.fillStyle=conceptPalette.muted;context.font=`700 ${size.width<560?9:10}px system-ui`;context.textAlign="left";context.fillText(size.width<560?"0 → 1 · −2 → 0.01 · values < −4 clipped":"0 = influence 1 · −2 = influence 0.01 · values below −4 are clipped",margin,bottomChart.y+bottomChart.h+32);conceptState.stateAreas=conceptState.sequence.map((_,index)=>({x:topChart.x+index/Math.max(1,conceptState.sequence.length-1)*topChart.w-13,y:topChart.y-8,w:26,h:topChart.h+24,index}));conceptState.gateAreas=[];
  };
  const updateExplanation=(rnnStates,lstmStates,rnnInfluence,lstmInfluence)=>{
    const index=conceptState.step,state=(conceptState.model==="rnn"?rnnStates:lstmStates)[index],formula=$("#rnnFormula"),math=$("#rnnMath"),readout=$("#rnnReadout");
    if(conceptState.model==="rnn"){
      if(formula)formula.innerHTML=conceptState.activation==="linear"?"hₜ = wₓxₜ + ahₜ₋₁":"hₜ = tanh(wₓxₜ + ahₜ₋₁)";
      if(math)math.innerHTML=`At step ${index+1}: z = ${fmt(conceptState.inputWeight,2)}(${fmt(state.x,2)}) + ${fmt(conceptState.recurrent,2)}(${fmt(state.previousH,2)}) = <b>${fmt(state.z,3)}</b>, giving h = <b>${fmt(state.h,3)}</b>.`;
      if(readout)readout.innerHTML=`<strong>Simple RNN:</strong> local recurrent sensitivity is ${fmt(Math.abs(state.localInfluence),3)}. The first input's influence here is ${fmt(rnnInfluence[index],4)}.`;
    }else{
      if(formula)formula.innerHTML="cₜ = fₜcₜ₋₁ + iₜgₜ &nbsp; · &nbsp; hₜ = oₜ tanh(cₜ)";
      if(math)math.innerHTML=`At step ${index+1}: c = ${fmt(state.f,2)}(${fmt(state.previousC,2)}) + ${fmt(state.i,2)}(${fmt(state.g,2)}) = <b>${fmt(state.c,3)}</b>; h = ${fmt(state.o,2)} tanh(${fmt(state.c,3)}) = <b>${fmt(state.h,3)}</b>.`;
      if(readout)readout.innerHTML=`<strong>${conceptState.selectedGate[0].toUpperCase()+conceptState.selectedGate.slice(1)} gate:</strong> ${gateDescriptions[conceptState.selectedGate]}. Its current value is ${fmt({forget:state.f,input:state.i,candidate:state.g,output:state.o}[conceptState.selectedGate],3)}.`;
    }
  };
  conceptRender=()=>{
    const rnnStates=forward("rnn"),lstmStates=forward("lstm"),rnnInfluence=rnnPlayInfluence(conceptState.sequence,"rnn",options()),lstmInfluence=rnnPlayInfluence(conceptState.sequence,"lstm",options()),size=conceptSize(),context=conceptContext,currentRnn=rnnStates[conceptState.step],currentLstm=lstmStates[conceptState.step];context.clearRect(0,0,size.width,size.height);context.fillStyle="#f8fbfd";context.fillRect(0,0,size.width,size.height);syncEditorHighlight();
    if(conceptState.view==="mechanism"){conceptElements.plotLabel.textContent=conceptState.model==="rnn"?"Simple recurrence":"Gated recurrence";conceptElements.plotTitle.textContent=conceptState.model==="rnn"?"One state repeatedly transformed":"Inside the LSTM memory cell";const states=conceptState.model==="rnn"?rnnStates:lstmStates;drawTimeline(context,size,states,conceptState.model);conceptState.model==="rnn"?drawRnnCell(context,size,currentRnn,rnnInfluence[conceptState.step]):drawLstmCell(context,size,currentLstm)}
    else{conceptElements.plotLabel.textContent="Memory comparison";conceptElements.plotTitle.textContent="RNN and LSTM on the same sequence";drawComparison(context,size,rnnStates,lstmStates,rnnInfluence,lstmInfluence)}
    if(conceptState.view==="compare")metricCards([{label:"RNN hidden state",value:fmt(currentRnn.h,3),note:`At step ${conceptState.step+1}`},{label:"LSTM hidden state",value:fmt(currentLstm.h,3),note:`Cell memory ${fmt(currentLstm.c,3)}`},{label:"RNN first-input influence",value:fmt(rnnInfluence[conceptState.step],4),note:rnnInfluence[conceptState.step]<.02?"Mostly vanished":rnnInfluence[conceptState.step]>1?"Growing":"Still measurable"},{label:"LSTM first-input influence",value:fmt(lstmInfluence[conceptState.step],4),note:lstmInfluence[conceptState.step]<.02?"Mostly vanished":"Still measurable"}]);
    else if(conceptState.model==="rnn")metricCards([{label:"Current input",value:fmt(currentRnn.x,2),note:`x at step ${conceptState.step+1}`},{label:"Previous hidden",value:fmt(currentRnn.previousH,3),note:"Incoming memory"},{label:"Weighted sum",value:fmt(currentRnn.z,3),note:"Before activation"},{label:"Current hidden",value:fmt(currentRnn.h,3),note:`First-input influence ${fmt(rnnInfluence[conceptState.step],4)}`}]);
    else{const values=[currentLstm.f,currentLstm.i,Math.abs(currentLstm.g),currentLstm.o],labels=["forget","input","candidate","output"],largest=labels[values.indexOf(Math.max(...values))];metricCards([{label:"Cell memory",value:fmt(currentLstm.c,3),note:`Previous ${fmt(currentLstm.previousC,3)}`},{label:"Hidden state",value:fmt(currentLstm.h,3),note:"Visible recurrent output"},{label:"Strongest gate",value:largest,note:`Selected ${conceptState.selectedGate}`},{label:"First-input influence",value:fmt(lstmInfluence[conceptState.step],4),note:"Local sensitivity"}])}
    updateExplanation(rnnStates,lstmStates,rnnInfluence,lstmInfluence);
  };
  const moveStep=amount=>{stopConceptAnimation();conceptState.step=(conceptState.step+amount+conceptState.sequence.length)%conceptState.sequence.length;updateStepControl();conceptRender()};
  document.querySelectorAll('input[name="rnnView"]').forEach(input=>input.addEventListener("change",event=>{if(event.target.checked){conceptState.view=event.target.value;conceptRender()}}));
  $("#rnnPreset").value=conceptState.preset;$("#rnnPreset").addEventListener("change",event=>{stopConceptAnimation();conceptState.preset=event.target.value;if(RNN_PLAY_PRESETS[conceptState.preset])conceptState.sequence=[...RNN_PLAY_PRESETS[conceptState.preset].values];conceptState.step=0;renderSequenceEditor();updateStepControl();conceptRender()});
  $("#rnnModel").value=conceptState.model;$("#rnnModel").addEventListener("change",event=>{stopConceptAnimation();conceptState.model=event.target.value;updateCellControls();conceptRender()});$("#rnnActivation").value=conceptState.activation;$("#rnnActivation").addEventListener("change",event=>{conceptState.activation=event.target.value;conceptRender()});
  bindRange("rnnInputWeight",value=>conceptState.inputWeight=value,1);bindRange("rnnStrength",value=>conceptState.recurrent=value,2);bindRange("rnnForget",value=>conceptState.forgetBias=value,1);bindRange("rnnWrite",value=>conceptState.writeBias=value,1);
  $("#rnnStep").addEventListener("input",event=>{conceptState.step=Number(event.target.value)-1;$("#rnnStepOut").textContent=`${conceptState.step+1} / ${conceptState.sequence.length}`;conceptRender()});$("#rnnPrevious").addEventListener("click",()=>moveStep(-1));$("#rnnNext").addEventListener("click",()=>moveStep(1));
  $("#rnnAuto").addEventListener("click",()=>{if(conceptTimer){stopConceptAnimation();return}$("#rnnAuto").textContent="Pause";conceptTimer=setInterval(()=>{conceptState.step=(conceptState.step+1)%conceptState.sequence.length;updateStepControl();conceptRender()},window.labDelay?window.labDelay(650):650)});
  $("#rnnAdd").addEventListener("click",()=>{if(conceptState.sequence.length>=10)return;stopConceptAnimation();conceptState.sequence.push(0);conceptState.preset="custom";$("#rnnPreset").value="custom";renderSequenceEditor();updateStepControl();conceptRender()});$("#rnnRemove").addEventListener("click",()=>{if(conceptState.sequence.length<=3)return;stopConceptAnimation();conceptState.sequence.pop();conceptState.preset="custom";$("#rnnPreset").value="custom";conceptState.step=Math.min(conceptState.step,conceptState.sequence.length-1);renderSequenceEditor();updateStepControl();conceptRender()});$("#rnnReset").addEventListener("click",()=>{stopConceptAnimation();conceptState.step=0;updateStepControl();conceptRender()});
  conceptPointerDown=event=>{const position=conceptPosition(event),gate=conceptState.gateAreas.find(area=>position.x>=area.x&&position.x<=area.x+area.w&&position.y>=area.y&&position.y<=area.y+area.h);if(gate){conceptState.selectedGate=gate.gate;conceptRender();return}const state=conceptState.stateAreas.find(area=>position.x>=area.x&&position.x<=area.x+area.w&&position.y>=area.y&&position.y<=area.y+area.h);if(state){stopConceptAnimation();conceptState.step=state.index;updateStepControl();conceptRender()}};conceptKeyDown=event=>{if(!["ArrowLeft","ArrowRight"].includes(event.key))return;event.preventDefault();moveStep(event.key==="ArrowRight"?1:-1)};
  conceptCanvas.style.cursor="pointer";conceptCanvas.setAttribute("aria-label","Interactive RNN and LSTM sequence. Click a time step or LSTM gate; use left and right arrow keys to move through the sequence.");renderSequenceEditor();updateStepControl();updateCellControls();conceptRender();
}

CONCEPT_SETUPS.rnn=setupRnnPlayground;
